// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auomchbootmdoqmaanlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1b21jaGJvb3RtZG9xbWFhbmx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTI0NDUsImV4cCI6MjA2MDQ4ODQ0NX0.T-GbJgEtHcuTjfoZtk9UmOWkMFKvYHfkkC-GavkakvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);